### ISSUE TITLE
Black screen after minimizing the window in Windows 7

### ISSUE THREAD

**Issue by chosenofbear** [Ancurio/mkxp#113]
If I minimize the window in Windows 7 and reopen it, the window will become black. The game is still running, because when I click the key, I can still hear the sound. This happens with both mingw and visual C++ builds.

**Comment by Ancurio** [comment]
There is no way for me (or I would guess anyone else) to reproduce your problem because it sounds very hardware/driver specific. mkxp always redraws the game screen independent of minimization, and as you reported, the game logic didn't freeze, so it's likely the frames simply don't make it to your screen.

Please verify that you have the latest graphics drivers installed on your system.
