### ISSUE TITLE
Win32 API Implementation

### ISSUE THREAD

**Issue by a-zer0** [Ancurio/mkxp#129]
Hey there, I <3 your project, thanks for making this!
I was thinking about helping you out a bit, and if possible I would like to take the Win32API Calls porting on me.

**Comment by Ancurio** [comment]
That's a pretty bold statement :) Are you intending to reimplement the entire Windows API?

**Comment by a-zer0** [comment]
Not the full API, just pieces that are logical to have in games as I'm sure Virtual Hard Disks are not needed for games :)

**Comment by Ancurio** [comment]
Which game in specific are you trying to make run under mkxp?

**Comment by a-zer0** [comment]
None in specific really, a friend just told me about this project and your effort, and I'm just trying to help, him a bit with rewriting some Win32 API calls, for linux and OSx :)

**Comment by Ancurio** [comment]
Just FYI, I don't think generally going ahead and implementing Win32 is a good idea.. first and foremost, mkxp is an implementation of RGSS, which the Windows API, or any other dlls, are not a part of. Second I try to be very conservative when exposing non-standard stuff (under the `MKXP` module) to write these win32 wrapper/implementation scripts; only if there's an (older) game that absolutely needs windows calls, that we're trying to make run under mkxp.

New games should not rely on external dll's as best as they can to be cross-platform, but of course I can't enforce that.. I just don't want to encourage it via mkxp =/

I'm sorry if the Readme is very ambiguous in this regard, "Win32API" should not be under "Things that don't work (yet)" because it was never supposed to be a part of mkxp.
