### ISSUE TITLE
A Guide to running RPGmaker games on Mkxp for total computer noobs?

### ISSUE THREAD

**Issue by gibzx** [Ancurio/mkxp#152]
Hi! would anyone be so kind as to make a step by step guide on how to run an RPGmaker game on mkxp? I am a complete computer noob, and even more so on linux which i only started using a week ago. So far i have downloaded mkxp, and the game i want to play, and im completely stumped on what to do next. I'm very sorry to be such trouble, but I rarely understand command lines and what not, I need someone to tell me what to do, (copy paste this on my terminal, move the files here or there). thanks!

**Comment by Ancurio** [comment]
Hello!

A lot of RPGMaker games out there, especially the bigger ones, use scripts that call directly into native Windows functions; there are ways to work around those, but sometimes this is non-trivial (and mkxp doesn't at all try to reimplement WINE).

I'd hate to give you instructions, only for the game not working due to errors. Is the game you're trying to play encrypted? If not, upload the `Data/Scripts` file and give me a link, I'll take a look at whether it is runnable with an unextended mkxp executable at all. If it's encrypted, you can also upload the encrypted archive (usually called "Game.rgssad" or similar), but that tends to be a bit bigger in size.

**Comment by gibzx** [comment]
@Ancurio thanks for the reply Ancurio, and well, oh my, I'd love to give you the game files to check it out, but I must warn you, its kind of an... "Adult" game, as in an H-game, very pornographic to say the least, quite common here in Japan.

I wouldn't want you to feel uncomfortable my making you help me run a hentai game, knowing that these games or not very common in other countries...  so I feel I need to ask you if you are ok beforehand if sent you the files even if they are of NSFW nature? it being an H-game and all. If you still feel like helping out to run this game, I would appreciate it very much ^,^

**Comment by Ancurio** [comment]
Don't worry, I just need to look at the code controlling the game logic. I promise I won't look at any art assets.

Send me the link at Nyocurio@gmail.com

**Comment by Slider-Whistle** [comment]
I know this is an old-ass issue, but it might help to add a little introductory paragraph to the readme.

**Comment by Ancurio** [comment]
@Slider-Whistle I'll add a part about that to the README

**Comment by Ancurio** [comment]
Closing to declutter, I don't remember being able to finish this port, sorry about that.
