### ISSUE TITLE
Win32API

### ISSUE THREAD

**Issue by buddysievers** [Ancurio/mkxp#182]
Hey and hello there,
i really like this project and it runs fine so far on my project
The performance is just awesome, no lags at all so far.
Only the Win32API functions dont work like you said in "What doesn't work (yet)".
Do you plan to integrate them as well anytime soon?
I dont plan to release my game under Linux or OSX, i just want to use mkxp for the performance
so is there maybe a way to unlock the functions for Windows only builds?
Sorry to post here but i didnt found topics about this on the rpgmaker communitys and there was no way to contact the developer.
Thx in advance! :)

**Comment by Ancurio** [comment]
No, I don't plan on ever supporting Win32API because mkxp is meant to be (desktop) OS agnostic, and Win32API has been deprecated/removed in Ruby 2.1 anyway. Sorry, but you're on your own.

There are a few scripts by me floating around that implement a small subset of Win32API on top of mkxp's extensions, such as this one: https://pastebin.com/raw/zXW1hdrx

Other than that, you're on your own. Sorry.

**Comment by buddysievers** [comment]
Thx for the fast reply i will see if i can replace some scripts by pure ruby methods instead.
But great work so far!
