### ISSUE TITLE
Does mkxp recognize multiple RTPs?

### ISSUE THREAD

**Issue by KainNobel** [Ancurio/mkxp#245]
Hello Ancurio and friends,

I'm curious if mkxp has support for multiple RTPs? I have 3 that I use. Does it only read RTP Standard or does it read all 3 as defined in the Game.ini file? I know it all has something to do with the Windows Registry, but I don't know if your system is setup to know how to do all that or if I have to do $LOAD_PATH << or what.

RTP1=Kain Nobel
RTP2=Standard
RTP3=Public Domain

I need to load all 3 of these.

**Comment by cremno** [comment]
[It should support multiple RTP but you have to manually specify their paths.](https://github.com/Ancurio/mkxp/blob/380b676777b101a7d6648a8e6b9a226a8984bbc0/mkxp.conf.sample#L219-L225) since the Windows Registry doesn't exist on mac or other operating systems. Btw. the original RGSS supports up to 9 RTP.

**Comment by Ancurio** [comment]
I should probably print a fat warning on startup that RTPs specified in the Game.ini are being ignored..
