### ISSUE TITLE
Compatibility List

### ISSUE THREAD

**Issue by RyanBram** [Ancurio/mkxp#91]
Hi, Jonas.
First of all I want to say thank you for creating MKXP.

I tried your pre-build Windows Binary of MKXP for playing several games, such as Exit Fate, Dark Gaia's One Night Series, etc. Unfortunately all of them is unplayable.

Is the project's goal for playing games already made with RPG Maker unmodified to non-Windows platform or for game developers who want to port their game although need modification in their scripts?

If the goal is the first, it will be nice if someone (or me) provide a compatibility list of games to show how much progress that MKXP achieve. But if the goal is the later, compatibility list isn't necessary as the game developers still need to patch their game themselves.

Regards

**Comment by cremno** [comment]
Modification is not always necessary, but I see two major incompatibility issues:

- mkxp uses a newer Ruby version (> 2.0.0): scripts, especially of XP and VX games, likely have to be modified. Their respective RGSS versions embed 1.8.1 (which was released in 2003!). It isn't easy to compile that version nowadays. And I'm not totally sure, but I believe it doesn't even properly support x86_64. Of course, one could try forking mkxp to make it work with 1.8.6 or even 1.8.7. VX Ace scripts usually don't require modifications, unless:

- There is a significant amount of games that make use of DLLs and Win32API/dl. Those game need also to be modified to support other operating systems. mkxp has some extensions that an be used instead. DLLs that manipulate bitmaps (like Mode 7) can't be used at all, since mkxp doesn't use GDI bitmaps.

>Unfortunately all of them is unplayable.

Can you provide some details? Unplayable can mean pretty much anything. It could be something that isn't related to the two issues above, like graphical problems that can and need to be fixed.

**Comment by Ancurio** [comment]
Thanks for answering the bulk of it, cremno.

The issue with RPG Maker games is that in theory, RGSS can be a cross platform base engine to write games (the default scripts even user forward slashes in file paths); however due to Ruby making it easy to call native code, you would in theory need something on the scale of the wine project to faithfully play every single game "without a change", and as cremno mentioned, there are even native DLLs that rely on undocumented RPG Maker internals. Obviously that's out of scope for a mostly one-man project like mkxp, so compromises have to be made.

Regarding the Ruby version, I was actually able to compile a 1.8.x source tarball without any hiccups, but I haven't looked yet into how painful it would be to adapt the current MRI binding code to work with it. Of course, using a pre 1.9 version of Ruby would also mean losing the speed advantage of compiled bytecode. But it's something that has been on my mind.

As an example of a relatively popular game which works under mkxp without a single change, there's [Majo no Ie](http://majonoie.karou.jp/), a VX game.

As for your question, I started writing mkxp with the primary intent of empowering users to play RPG Maker games on whatever PC OS they wish to, so if changes to scripts have to be done, I'd like them to be as minimal as possible. I don't think the two goals you stated are mutually exclusive though.

**Comment by RyanBram** [comment]
Thanks for detailed explanation.

Now I understood the intention of MKXP. Game compatibility list seems impractical, as MKXP isn't intended to replace every function calls from RPG Maker especially if they are depend on Windows native functions.

Although game compatibility list seems impractical, I think script compatibility list still worth to be documented. There are many free scripts in internet which are very popular and by documenting compatibility list hopefully will help user or script maker to fix those compatibility issues.

If you agree with that, I may start to test many scripts that I knew and documenting it in my free time.

Regards
