### ISSUE TITLE
The Mirror Lied 2.0 unitialized constant StartGame::Win32API

### ISSUE THREAD

**Issue by adrenochrome25** [Ancurio/mkxp#95]
can't run the current version (2.0) of "The Mirror Lied" on linux
the Gui open an error windows reporting : 
unitialized constant StartGame::Win32API

the terminal traces : 
GL Vendor    : ATI Technologies Inc. 
GL Renderer  : AMD Mobility Radeon HD 5800 Series 
GL Version   : 4.4.13283 Compatibility Profile Context 14.501.1003 
GLSL Version : 4.40 
Had exception: NameError 
["eval:12:in `<module:StartGame>'", "eval:3:in`<main>'"]

i tried to dl the release(0.8) from this forum : 
 http://freebirdgames.com/forum/index.php?topic=5064.0
which work correctly
when i replace the game/ files with those from 2.0 i get same error as above
same error too with latest mkxp (mkxp-20150204.tar.xz )

**Comment by openmac** [comment]
As far as I know the 0.8 version number is for the Linux port and is not the game version itself, therefore it should be the latest version of the game and you don't need to download a newer version.

The reason you get that error with files taken from the Windows version is because of a call on Win32API which is not supported on mkxp and is removed from the Linux port of the game.

If you still prefer to play the Windows version with mkxp, you have to either edit the scripts of the game to remove that Win32API or use something similar to this win32_wrap.rb script:
http://pastebin.com/zXW1hdrx

You can add it to preload scripts in the mkxp.conf file.

(I have not tried the above win32 wrapper script with The Mirror Lied, but the process is similar).
